### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by fjbanares** [BSData/harry-potter#3]
Hello! I will help to update this repository, because @amis92 is a bit bussy lately.

Thanks you so much. Regards.

**Comment by amis92** [comment]
@nexomad is the maintainer here.

**Comment by nexomad** [comment]
Hello @amis92. I've been talking to @fjbanares about adding him as a contributor to the Harry Potter repository. I don't see the option to add him, how could I? Or is it an administration task that has to be done by you?

**Comment by amis92** [comment]
> Or is it an administration task that has to be done by you?

It is indeed. You can accept Pull Requests though. I'll invite @fjbanares as I think that's what you want though.

@fjbanares 
https://github.com/BSData/harry-potter/invitations
